// <auto-generated />
namespace EE5207.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class conducteddaysadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conducteddaysadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202002071850178_conducteddaysadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
